### ISSUE TITLE
Recieving error (date and time) json: unknown field "needIssueSync"

### ISSUE THREAD

**Issue by levelfourtwenty** [deletescape/sloot#5]
When trying to use the program I receive an error containing `(date and time) json: unknown field "needIssueSync"`, I've made sure I was using the newest version and tried on two different devices with the same error happening. I've made sure the sonarqube is accessible as well.

**Comment by nyancrimew** [comment]
I have finally fixed this now, that field has been introduced in a recent version of SonarQube and was not yet in the model
